Stackv2
r-three/common-pile pull request #72
Opened 2024-05-14 19:18 UTC by Muennighoff

2024-05-25 22:08 UTC, Muennighoff commented
Still waiting for the dataset to be released (hopefully soon), but does this look more or less reasonable @blester125 ? Is there anything else I can do while the DS is not yet released?

2024-05-25 22:46 UTC, blester125 requested changes
There are a few copy paste errors to clean up, but other than that it looks good to merge.

I'm also fine with merging it before the datasets go public

2024-05-25 22:46 UTC, blester125 commented on stackv2/to_dolma.py
> +logger = configure_logging("court-listener-opinion")
copypasta lol

2024-05-25 22:46 UTC, blester125 commented on stackv2/to_dolma.py
> +    output_file_base_name = os.path.join(args.output_dir, "starcoder2data.jsonl.gz")
You don't need to join the output_dir and `"startcoder2data.jsonl.gz"`, you should just pass the latter.

2024-05-25 22:46 UTC, blester125 commented on stackv2/to_dolma.py
> +    parser = argparse.ArgumentParser(description="Convert csv data to dolma.")
convert HF data to dolma

2024-05-25 22:46 UTC, blester125 commented on stackv2/sample.json
What is this file? Fake data that has the same format as the HF data once loaded? Is there a reason to check it in?

2024-05-25 22:46 UTC, blester125 commented on stackv2/to_dolma.py
> +        "--data_dir", type=str, default=None, help="Optionally select a language"
I'm assuming this selects a subset of the dataset based on language? Can you add info on where to see the possible languages? Also, even if it is used as the "data_dir" later we should expose it to the user with a more self-descriptive name like "language".

2024-05-25 23:25 UTC, Muennighoff commented on stackv2/sample.json
Yeah it is how the dataset will look like once uploaded. Should I remove it?

2024-05-26 00:19 UTC, blester125 approved these changes

2024-05-26 00:19 UTC, blester125 commented on stackv2/to_dolma.py
> +        type=str,
Nit: `type=str` is the default, not needed.

2024-05-26 00:19 UTC, blester125 commented on stackv2/sample.json
I think it fine either way, we just need to remember to remove it once the dataset is released.

2024-05-26 06:04 UTC, Muennighoff commented on stackv2/to_dolma.py
> +        type=str,
```suggestion
```

2024-05-27 17:16 UTC, Muennighoff commented
Should we preliminarily merge this @blester125 ? Will create a new PR then once the data is released to make the necessary changes.

2024-05-28 18:31 UTC, merged