Add domain counting script
r-three/common-pile pull request #91
Opened 2024-09-20 03:52 UTC by wildphoton

Script for extracting the sub-urls and counting their frequency and total-text-length in CCCC dataset.

2024-10-14 22:09 UTC, blester125 requested changes
There are linting error that need to be fixed too

2024-10-14 22:09 UTC, blester125 commented on dolma-cccc/domain_counter.py
> +    for part in path_parts[:-1]:
Why are you indexing with `[:-1]` here? In the `path_parts` line you have `.strip('/')` so it seems like this function is ok with the final part of the path being a directory (and therefore should be part of this suburl list) but it gets filtered out?

2024-10-14 22:09 UTC, blester125 commented on dolma-cccc/domain_counter.py
> +        with ProcessPoolExecutor(max_workers=40) as executor:  # Adjust max_workers based on your system
This max worker should be a cli argument if you want people to adjust it themselves

2024-10-14 22:09 UTC, blester125 commented on dolma-cccc/domain_counter.py
> +    sorted_suburls = sorted(final_suburl_counter.items(), key=lambda item: item[1], reverse=True)
You're using a counter object, you can do `final_suburl_counter.most_common(10)` to get the top 10 sub urls by frequency.

2024-10-14 22:09 UTC, blester125 commented on dolma-cccc/domain_counter.py
> +    sorted_text_lengths = sorted(final_text_length_counter.items(), key=lambda item: item[1], reverse=True)
Same as above

2024-10-14 22:09 UTC, blester125 commented on dolma-cccc/domain_counter.py
> +    sorted_text_lengths = sorted(final_text_length_counter.items(), key=lambda item: item[1], reverse=True)
Something like

```
import operator as op

... = sorted(..., key=op.itemgetter(1), ...)
```

is generally preferred over a lambda to get a item like this

2024-10-14 22:09 UTC, blester125 commented on dolma-cccc/domain_counter.py
> +                # If counts match, mark the higher-level URL for removal
The term `higher-level` is confusing, it makes it seem like you would be removing the parent url.

2024-10-14 22:09 UTC, blester125 commented on dolma-cccc/domain_counter.py
> +token = "YOUR_HF_TOKEN"  # Replace with you own hf token if you want to submit the dataset
This should be a cli argument.

2024-10-14 22:09 UTC, blester125 commented on dolma-cccc/domain_counter.py
> +snapshot_download(repo_id="allenai/dolma-cccc", local_dir='data/dolma-cccc', repo_type="dataset")
This should all be wrapped into a `main` function

2025-06-19 19:13 UTC, craffel commented
We don't need this currently so I'll close it out, but good to have it around for reference, thanks.

2025-06-19 19:13 UTC, closed without merging